# Generated by Django 3.0 on 2019-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191216_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_type',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.PositiveIntegerField(),
        ),
    ]
