# Generated by Django 3.0 on 2019-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191217_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
